yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreateModel, PubDateModel
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.constraints import UniqueConstraint

User = get_user_model()
COUNT_SYMBOL = 15


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='URL-ярлык')
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name_plural = 'Группы'


class Post(PubDateModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Название группы',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return self.text[:COUNT_SYMBOL]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(CreateModel):
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='comments',
        verbose_name='Автор'
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )

    def __str__(self) -> str:
        return self.text

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    UniqueConstraint(fields=['user', 'author'], name='follow_unique')

    def __str__(self) -> str:
        return self.user

yatube/posts/forms.py
from django import forms

from .models import Comment, Follow, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_post(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Напишите пост!')
        return data


class FollowForm(forms.ModelForm):
    class Meta:
        model = Follow
        fields = ('user', 'author',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

    def clean_post(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Напишите пост!')
        return data

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

NUMBER_OF_POSTS: int = 10


def index(request):
    template = 'posts/index.html'
    posts_list = Post.objects.all()
    paginator = Paginator(posts_list, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.posts.all()
    paginator = Paginator(posts_list, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    profile_user = get_object_or_404(User, username=username)
    user = request.user
    posts_count = profile_user.posts.count()
    posts_list_username = profile_user.posts.all()
    paginator = Paginator(posts_list_username, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if user.is_authenticated:
        following = None
        if profile_user != user:
            following = False
            if profile_user.following.exists():
                following = True
    context = {
        'user': user,
        'following': following,
        'profile_user': profile_user,
        'page_obj': page_obj,
        'posts_count': posts_count,
    }
    return render(request, 'posts/profile.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


def post_detail(request, post_id):
    post_user = get_object_or_404(Post, id=post_id)
    posts_count = post_user.author.posts.count()
    comments = post_user.comments.filter(post_id=post_id)
    form_comments = CommentForm(request.POST or None)
    context = {
        'post_user': post_user,
        'posts_count': posts_count,
        'comments': comments,
        'form_comments': form_comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post.id)

    is_edit = post.text
    context = {
        'is_edit': is_edit,
        'form': form,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def follow_index(request):
    author_ids = Follow.objects.filter(user=request.user).values_list(
        'author_id',
        flat=True
    )
    posts_list = Post.objects.filter(author_id__in=author_ids)
    paginator = Paginator(posts_list, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
        return redirect('posts:profile', author.username)
    else:
        return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', author.username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {% if is_edit %}
    Редактировать запись {{ is_edit }}
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                    Текст поста
                    <span class="required text-danger" >*</span>
                </label>
                {% if is_edit %}
                  <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    {{ is_edit }}
                  </textarea>
                {% else %}
                  <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                  </textarea>
                {% endif %}
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа
                </label>
                {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <p>Картинка</p>
              <p>{{ form.image }}</p>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить запись
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Подписки
{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  <h1>Подписки</h1>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          {% if post.author.get_full_name %}
            Автор: {{ post.author.get_full_name }}
          {% else %}
            Автор: {{ post.author.username }}
          {% endif %}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y"}}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
       <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" >
      {% endthumbnail %}
      <p>{{ post.text }}</p>
    <article>
    <ul>
        <a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a>
    </ul>
    <ul>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
      {% endif %}
    </ul>
    <ul>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
    </ul>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          {% if post.author.get_full_name %}
            Автор: {{ post.author.get_full_name }}
          {% else %}
            Автор: {{ post.author.username }}
          {% endif %}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a></p>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y"}}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
      <br>
      <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
    <article>
    {% if not forloop.last %}<hr>{% endif%}
  {% endfor %}

{% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
{% cache 20 index_page page_obj %}
  {% include 'posts/includes/switcher.html' %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          {% if post.author.get_full_name %}
            Автор: {{ post.author.get_full_name }}
          {% else %}
            Автор: {{ post.author.username }}
          {% endif %}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y"}}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
       <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" >
      {% endthumbnail %}
      <p>{{ post.text }}</p>
    <article>
    <ul>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
      {% endif %}
    </ul>
    <ul>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
    </ul>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
{{ post_user }}
{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post_user.pub_date|date:"d E Y" }}
      </li>
        {% if post_user.group %}
          <li class="list-group-item">
            Группа: {{ post_user.group }}
          </li>
        {% endif %}
              <li class="list-group-item">
                {% if post_user.author.get_full_name %}
                  Автор: {{ post_user.author.get_full_name }}
                {% else %}
                  Автор: {{ post_user.author.username }}
                {% endif %}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post_user.author.username %}">
                Все посты пользователя
              </a>
            </li>
            {% if post_user.group %}
              <li class="list-group-item">
                <a href="{% url 'posts:group_list' post_user.group.slug %}">
                  Все записи группы
                </a>
              </li>
            {% endif%}
            {% if request.user.username == post_user.author.username %}
            <li class="list-group-item">
              <a href="{% url 'posts:post_edit' post_user.id %}">
                Редактировать запись
              </a>
            </li>
            {% endif %}
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post_user.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
          <p>
            {{ post_user.text }}
          </p>
          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post_user.id %}">
                {% csrf_token %}
                <div class="form-group mb-2">
                  {{ form_comments.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
          {% endif %}
          {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                 {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Профайл пользователя {{ profile_user.username }}
{% endblock %}
{% block content %}
<div class="mb-5">
  <h1>
    Все посты пользователя
    {% if profile_user.get_full_name %}
      {{ profile_user.get_full_name }}
    {% else %}
      {{ profile_user.username }}
    {% endif %}
  </h1>
  <h3>Всего постов:  {{ posts_count }} </h3>

    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' profile_user.username %}" role="button"
    >
      Отписаться
    </a>
    {% elif following == False %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' profile_user.username %}" role="button"
      >
        Подписаться
      </a>
    {% elif following == None %}
       <p>Это Ваши посты</p>
    {% endif %}


</div>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            {% if profile_user.get_full_name %}
              Автор: {{ profile_user.get_full_name }}
            {% else %}
              Автор: {{ profile_user.username }}
            {% endif %}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}